api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "designer-pricing"
type = "function"
uid = "e23d370b-6ee2-b035-5a8d-56c1721efd1fb05caae3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
